import { LibraryItem } from "./data";

export const bnccData: LibraryItem[] = [
    // --- LÍNGUA PORTUGUESA (1º ao 5º ano) ---
    { id: "bncc-lp-ef01lp01", type: "skill", code: "EF01LP01", name: "Sistema de escrita alfabética", description: "Reconhecer que textos são lidos e escritos da esquerda para a direita e de cima para baixo da página.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-lp-ef01lp02", type: "skill", code: "EF01LP02", name: "Escrita autônoma", description: "Escrever, espontaneamente ou por ditado, palavras e frases de forma alfabética – usando letras/grafemas que representem fonemas.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-lp-ef01lp05", type: "skill", code: "EF01LP05", name: "Compreensão de leitura", description: "Reconhecer o sistema de escrita alfabética como representação dos sons da fala.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-lp-ef02lp01", type: "skill", code: "EF02LP01", name: "Leitura de palavras", description: "Utilizar, ao produzir o texto, grafia correta de palavras conhecidas ou com estruturas silábicas já dominadas.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-lp-ef02lp04", type: "skill", code: "EF02LP04", name: "Leitura e compreensão", description: "Ler e compreender, em colaboração com os colegas e com a ajuda do professor e, mais tarde, de maneira autônoma, textos curtos com nível de textualidade adequado.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-lp-ef03lp01", type: "skill", code: "EF03LP01", name: "Fluência de leitura", description: "Ler e compreender, com autonomia, textos breves com nível de textualidade adequado.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-lp-ef03lp05", type: "skill", code: "EF03LP05", name: "Produção de textos", description: "Identificar o número de sílabas de palavras, classificando-as em monossílabas, dissílabas, trissílabas e polissílabas.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-lp-ef04lp01", type: "skill", code: "EF04LP01", name: "Compreensão de textos", description: "Grafar palavras utilizando regras de correspondência fonema-grafema regulares diretas e contextuais.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-lp-ef04lp05", type: "skill", code: "EF04LP05", name: "Análise linguística", description: "Identificar a função na leitura e usar na escrita ponto final, ponto de interrogação, ponto de exclamação.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-lp-ef05lp01", type: "skill", code: "EF05LP01", name: "Estratégia de leitura", description: "Grafar palavras utilizando regras de correspondência fonema-grafema regulares, contextuais e morfológicas.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-lp-ef05lp15", type: "skill", code: "EF05LP15", name: "Compreensão de textos", description: "Ler/compreender e produzir contos, fábulas, lendas, mitos, relatos, entre outros, considerando a situação comunicativa.", isBNCC: true, subGroup: "Língua Portuguesa" },

    // --- MATEMÁTICA (1º ao 5º ano) ---
    { id: "bncc-ma-ef01ma01", type: "skill", code: "EF01MA01", name: "Números Naturais", description: "Utilizar números naturais como indicador de quantidade ou de ordem em diferentes situações cotidianas.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-ma-ef01ma06", type: "skill", code: "EF01MA06", name: "Adição e Subtração", description: "Construir fatos básicos da adição e utilizá-los em procedimentos de cálculo para resolver problemas.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-ma-ef01ma11", type: "skill", code: "EF01MA11", name: "Geometria Espacial", description: "Descrever a localização de pessoas e de objetos no espaço em relação à sua própria posição.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-ma-ef02ma01", type: "skill", code: "EF02MA01", name: "Sistema de Numeração Decimal", description: "Comparar e ordenar números naturais (até a ordem de centenas) pela compreensão de características do sistema de numeração decimal.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-ma-ef02ma05", type: "skill", code: "EF02MA05", name: "Problemas de Adição e Subtração", description: "Construir fatos básicos da adição e subtração e utilizá-los no cálculo mental ou escrito.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-ma-ef03ma03", type: "skill", code: "EF03MA03", name: "Multiplicação", description: "Construir e utilizar fatos básicos da adição e da multiplicação para o cálculo mental ou escrito.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-ma-ef03ma13", type: "skill", code: "EF03MA13", name: "Geometria de Figuras", description: "Associar figuras geométricas espaciais (cubo, bloco retangular, pirâmide, cone, cilindro e esfera) a objetos do mundo físico.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-ma-ef04ma02", type: "skill", code: "EF04MA02", name: "Problemas Aritméticos", description: "Mostrar, por decomposição e composição, que todo número natural pode ser escrito por meio de adições e multiplicações.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-ma-ef04ma17", type: "skill", code: "EF04MA17", name: "Decimais e Frações", description: "Associar frações 1/2, 1/3, 1/4, 1/5, 1/10 e 1/100 à ideia de divisão, a cilindros, tortas, pedaços de fitas.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-ma-ef05ma07", type: "skill", code: "EF05MA07", name: "Resolução de Problemas", description: "Resolver e elaborar problemas de adição e subtração com números naturais e com números racionais, cuja representação decimal seja finita.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-ma-ef05ma19", type: "skill", code: "EF05MA19", name: "Medidas", description: "Resolver e elaborar problemas envolvendo medidas das grandezas comprimento, área, massa, tempo, temperatura e capacidade.", isBNCC: true, subGroup: "Matemática" },

    // --- CIÊNCIAS (1º ao 5º ano) ---
    { id: "bncc-ci-ef01ci01", type: "skill", code: "EF01CI01", name: "Características dos Materiais", description: "Comparar características de diferentes materiais presentes em objetos de uso cotidiano.", isBNCC: true, subGroup: "Ciências" },
    { id: "bncc-ci-ef01ci02", type: "skill", code: "EF01CI02", name: "Corpo Humano", description: "Localizar e nomear partes do corpo humano, associando-as às suas funções e propondo atitudes de manutenção da saúde.", isBNCC: true, subGroup: "Ciências" },
    { id: "bncc-ci-ef02ci04", type: "skill", code: "EF02CI04", name: "Plantas e Animais", description: "Descrever características de plantas e animais (tamanho, forma, cor, fase da vida, local onde se desenvolvem).", isBNCC: true, subGroup: "Ciências" },
    { id: "bncc-ci-ef02ci07", type: "skill", code: "EF02CI07", name: "Sol e Sombras", description: "Descrever as posições do Sol em diversos horários do dia e associá-las ao tamanho da sombra projetada.", isBNCC: true, subGroup: "Ciências" },
    { id: "bncc-ci-ef03ci04", type: "skill", code: "EF03CI04", name: "Animais Vertebrados", description: "Identificar características sobre o modo de vida o que comem, como se reproduzem, como se deslocam de animais mais comuns no ambiente próximo.", isBNCC: true, subGroup: "Ciências" },
    { id: "bncc-ci-ef03ci07", type: "skill", code: "EF03CI07", name: "A Terra", description: "Identificar características da Terra (como seu formato esférico, a presença de água, solo etc.).", isBNCC: true, subGroup: "Ciências" },
    { id: "bncc-ci-ef04ci01", type: "skill", code: "EF04CI01", name: "Misturas", description: "Identificar misturas na vida diária, com base em suas propriedades físicas observáveis, reconhecendo sua composição.", isBNCC: true, subGroup: "Ciências" },
    { id: "bncc-ci-ef04ci05", type: "skill", code: "EF04CI05", name: "Teia Alimentar", description: "Descrever e destacar semelhanças e diferenças entre ciclo da matéria e fluxo de energia entre componentes vivos e não vivos.", isBNCC: true, subGroup: "Ciências" },
    { id: "bncc-ci-ef05ci02", type: "skill", code: "EF05CI02", name: "Ciclo da Água", description: "Aplicar os conhecimentos sobre as mudanças de estado físico da água para explicar o ciclo hidrológico.", isBNCC: true, subGroup: "Ciências" },
    { id: "bncc-ci-ef05ci08", type: "skill", code: "EF05CI08", name: "Nutrição Orgânica", description: "Organizar um cardápio equilibrado com base nas características dos grupos alimentares e nas necessidades individuais.", isBNCC: true, subGroup: "Ciências" },

    // --- HISTÓRIA (1º ao 5º ano) ---
    { id: "bncc-hi-ef01hi01", type: "skill", code: "EF01HI01", name: "O sujeito e seu lugar", description: "Identificar aspectos do seu crescimento por meio do registro das lembranças particulares ou de lembranças da família.", isBNCC: true, subGroup: "História" },
    { id: "bncc-hi-ef01hi04", type: "skill", code: "EF01HI04", name: "Fontes históricas", description: "Identificar as diferenças entre os variados ambientes de convivência (doméstico, escolar e da comunidade).", isBNCC: true, subGroup: "História" },
    { id: "bncc-hi-ef02hi01", type: "skill", code: "EF02HI01", name: "Tempo histórico", description: "Reconhecer espaços de sociabilidade e identificar os motivos que aproximam e separam as pessoas em diferentes lugares e tempos.", isBNCC: true, subGroup: "História" },
    { id: "bncc-hi-ef02hi04", type: "skill", code: "EF02HI04", name: "A comunidade", description: "Selecionar e compreender o significado de objetos e documentos pessoais como fontes de memórias e histórias.", isBNCC: true, subGroup: "História" },
    { id: "bncc-hi-ef03hi01", type: "skill", code: "EF03HI01", name: "Espaço urbano e rural", description: "Identificar os grupos populacionais que formam a cidade de residência e o município, destacando as suas origens culturais.", isBNCC: true, subGroup: "História" },
    { id: "bncc-hi-ef04hi01", type: "skill", code: "EF04HI01", name: "Circulação de pessoas", description: "Reconhecer a história como resultado da ação de diferentes grupos e sujeitos nos processos de organização social da cidade/município.", isBNCC: true, subGroup: "História" },
    { id: "bncc-hi-ef04hi04", type: "skill", code: "EF04HI04", name: "Primeiros habitantes do Brasil", description: "Identificar as rotas fluviais, marítimas e terrestres estabelecidas para comercialização entre os povos nativos da América.", isBNCC: true, subGroup: "História" },
    { id: "bncc-hi-ef05hi01", type: "skill", code: "EF05HI01", name: "Registros e memórias", description: "Identificar e analisar o papel das culturas e das religiões na estruturação das sociedades antigas.", isBNCC: true, subGroup: "História" },
    { id: "bncc-hi-ef05hi04", type: "skill", code: "EF05HI04", name: "Patrimônio cultural", description: "Associar a noção de cidadania e de direitos aos princípios de respeito à diversidade, no Brasil, em diferentes contextos históricos.", isBNCC: true, subGroup: "História" },

    // --- GEOGRAFIA (1º ao 5º ano) ---
    { id: "bncc-ge-ef01ge01", type: "skill", code: "EF01GE01", name: "O lugar e o sujeito", description: "Descrever características observadas de seus lugares de vivência (moradia, escola etc.) e identificar semelhanças e diferenças.", isBNCC: true, subGroup: "Geografia" },
    { id: "bncc-ge-ef01ge03", type: "skill", code: "EF01GE03", name: "Dinâmica do dia a dia", description: "Identificar e relatar semelhanças e diferenças de usos do espaço público (praças, parques) para o lazer e diferentes manifestações.", isBNCC: true, subGroup: "Geografia" },
    { id: "bncc-ge-ef02ge01", type: "skill", code: "EF02GE01", name: "O lugar de vivência", description: "Descrever a história das migrações no bairro ou comunidade em que vive.", isBNCC: true, subGroup: "Geografia" },
    { id: "bncc-ge-ef02ge08", type: "skill", code: "EF02GE08", name: "Paisagens", description: "Identificar e elaborar diferentes formas de representação (desenhos, mapas mentais, maquetes) para as paisagens.", isBNCC: true, subGroup: "Geografia" },
    { id: "bncc-ge-ef03ge01", type: "skill", code: "EF03GE01", name: "A cidade e o campo", description: "Identificar e comparar aspectos culturais dos grupos sociais de seus lugares de vivência, seja na cidade ou no campo.", isBNCC: true, subGroup: "Geografia" },
    { id: "bncc-ge-ef03ge04", type: "skill", code: "EF03GE04", name: "A cidade e a natureza", description: "Explicar como os processos naturais e históricos atuam na produção e na mudança das paisagens naturais e antrópicas nos seus lugares de vivência.", isBNCC: true, subGroup: "Geografia" },
    { id: "bncc-ge-ef04ge01", type: "skill", code: "EF04GE01", name: "Território brasileiro", description: "Selecionar na cidade ou na região de vivência, órgãos do poder público (Prefeitura, Câmara Municipal, Fórum) e identificar suas funções.", isBNCC: true, subGroup: "Geografia" },
    { id: "bncc-ge-ef04ge05", type: "skill", code: "EF04GE05", name: "Atividades na cidade", description: "Distinguir unidades interativas de poder, esferas e níveis (federal, estadual e municipal).", isBNCC: true, subGroup: "Geografia" },
    { id: "bncc-ge-ef05ge01", type: "skill", code: "EF05GE01", name: "Regiões Brasileiras", description: "Descrever a dinâmica populacional brasileira (crescimento e distribuição), destacando o papel da migração.", isBNCC: true, subGroup: "Geografia" },
    { id: "bncc-ge-ef05ge08", type: "skill", code: "EF05GE08", name: "Mapas e Tecnologias", description: "Analisar transformações observadas em paisagens nos lugares de vivência em razão do uso de diferentes tecnologias.", isBNCC: true, subGroup: "Geografia" },

    // --- ARTES (1º ao 5º ano) ---
    { id: "bncc-ar-ef15ar01", type: "skill", code: "EF15AR01", name: "Artes Visuais: Apreciação", description: "Identificar e apreciar formas distintas das artes visuais tradicionais e contemporâneas, cultivando a percepção.", isBNCC: true, subGroup: "Artes" },
    { id: "bncc-ar-ef15ar02", type: "skill", code: "EF15AR02", name: "Artes Visuais: Exploração", description: "Explorar e reconhecer elementos constitutivos das artes visuais (ponto, linha, forma, cor, espaço, movimento etc.).", isBNCC: true, subGroup: "Artes" },
    { id: "bncc-ar-ef15ar04", type: "skill", code: "EF15AR04", name: "Artes Visuais: Criação", description: "Experimentar diferentes formas de expressão artística (desenho, pintura, colagem, quadrinhos, dobradura, escultura etc.).", isBNCC: true, subGroup: "Artes" },
    { id: "bncc-ar-ef15ar08", type: "skill", code: "EF15AR08", name: "Dança: Exploração", description: "Experimentar e apreciar formas distintas de manifestações da dança de diferentes matrizes estéticas e culturais.", isBNCC: true, subGroup: "Artes" },
    { id: "bncc-ar-ef15ar13", type: "skill", code: "EF15AR13", name: "Música: Apreciação", description: "Identificar e apreciar criticamente diversas formas e gêneros de expressão musical.", isBNCC: true, subGroup: "Artes" },
    { id: "bncc-ar-ef15ar14", type: "skill", code: "EF15AR14", name: "Música: Exploração", description: "Perceber e explorar os elementos constitutivos da música (altura, intensidade, timbre, melodia, ritmo etc.).", isBNCC: true, subGroup: "Artes" },
    { id: "bncc-ar-ef15ar18", type: "skill", code: "EF15AR18", name: "Teatro: Apreciação", description: "Reconhecer e apreciar manifestações teatrais de diferentes matrizes e suas funções sociais.", isBNCC: true, subGroup: "Artes" },

    // --- EDUCAÇÃO FÍSICA (1º ao 5º ano) ---
    { id: "bncc-ef-ef12ef01", type: "skill", code: "EF12EF01", name: "Brincadeiras populares", description: "Experimentar, fruir e recriar diferentes brincadeiras e jogos da cultura popular presentes no contexto comunitário e regional.", isBNCC: true, subGroup: "Educação Física" },
    { id: "bncc-ef-ef12ef03", type: "skill", code: "EF12EF03", name: "Ação corporal", description: "Planejar e utilizar estratégias para a resolução de desafios em brincadeiras e jogos no contexto regional e comunitário.", isBNCC: true, subGroup: "Educação Física" },
    { id: "bncc-ef-ef12ef05", type: "skill", code: "EF12EF05", name: "Esportes de marca", description: "Experimentar esportes de marca e de precisão, discutindo sua origem, organização e suas regras.", isBNCC: true, subGroup: "Educação Física" },
    { id: "bncc-ef-ef12ef07", type: "skill", code: "EF12EF07", name: "Ginástica geral", description: "Experimentar, fruir e construir as ginásticas de conscientização corporal no contexto escolar.", isBNCC: true, subGroup: "Educação Física" },
    { id: "bncc-ef-ef35ef01", type: "skill", code: "EF35EF01", name: "Brincadeiras do Brasil", description: "Experimentar e recriar jogos e brincadeiras populares do Brasil, compreendendo sua diversidade cultural.", isBNCC: true, subGroup: "Educação Física" },
    { id: "bncc-ef-ef35ef05", type: "skill", code: "EF35EF05", name: "Esportes de Invasão", description: "Experimentar e valorizar diferentes esportes de marca, precisão, invasão e técnico-combinatórios.", isBNCC: true, subGroup: "Educação Física" },
    { id: "bncc-ef-ef35ef09", type: "skill", code: "EF35EF09", name: "Danças brasileiras", description: "Experimentar, recriar e fruir danças populares do Brasil e do mundo e danças de matriz indígena e africana.", isBNCC: true, subGroup: "Educação Física" },

    // --- CONTEÚDOS GERAIS BNCC (Mapeados) ---
    { id: "bncc-co-lp-01", type: "content", name: "Gêneros Textuais: Fábulas e Contos", description: "Estudo da estrutura de fábulas clássicas e contos folclóricos.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-co-lp-02", type: "content", name: "Pontuação e Entonação", description: "Utilização do ponto de interrogação, exclamação e final para dar sentido em leitura em voz alta.", isBNCC: true, subGroup: "Língua Portuguesa" },
    { id: "bncc-co-ma-01", type: "content", name: "Sistema Monetário Brasileiro", description: "Uso de cédulas e moedas para resolver problemas de troco e valores.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-co-ma-02", type: "content", name: "Figuras Geométricas Espaciais", description: "Identificação de prismas e pirâmides no ambiente escolar.", isBNCC: true, subGroup: "Matemática" },
    { id: "bncc-co-ci-01", type: "content", name: "Sistema Solar", description: "Introdução aos planetas e ao Sol como estrela central.", isBNCC: true, subGroup: "Ciências" },
    { id: "bncc-co-ci-02", type: "content", name: "Pirâmide Alimentar", description: "Classificação de grupos alimentares e hábitos saudáveis.", isBNCC: true, subGroup: "Ciências" },
    { id: "bncc-co-hi-01", type: "content", name: "História do Município", description: "Estudo sobre fundação e fatos marcos da cidade local.", isBNCC: true, subGroup: "História" },
    { id: "bncc-co-ge-01", type: "content", name: "Tipos de Moradia e Clima", description: "Como a localização geográfica impacta na construção das casas.", isBNCC: true, subGroup: "Geografia" },
    { id: "bncc-co-ar-01", type: "content", name: "Cores Quentes e Frias", description: "Estudo de composição de cores utilizando obras de Tarsila do Amaral.", isBNCC: true, subGroup: "Artes" },
    { id: "bncc-co-ef-01", type: "content", name: "Jogos Teatrais", description: "Expressão corporal utilizando mímicas para adivinhar regras.", isBNCC: true, subGroup: "Educação Física" },
];
