export const scheduleDataSeed = [
    {
        id: "1",
        time: "08:00",
        endTime: "09:00",
        title: "Chegada e Acolhimento",
        type: "care",
        description: "Recepção das crianças e brincadeira livre.",
        classId: "jardim-i",
        date: null,
        projectId: null,
        routineId: null
    },
    {
        id: "2",
        time: "09:00",
        endTime: "09:30",
        title: "Roda de Conversa",
        type: "activity",
        description: "Momento de compartilhar novidades e planejar o dia.",
        classId: "jardim-i",
        date: null,
        projectId: null,
        routineId: null
    },
    {
        id: "3",
        time: "09:30",
        endTime: "10:00",
        title: "Lanche da Manhã",
        type: "meal",
        description: "Frutas da estação e suco natural.",
        classId: "jardim-i",
        date: null,
        projectId: null,
        routineId: null
    },
    {
        id: "4",
        time: "10:00",
        endTime: "11:30",
        title: "Atividade de Pátio",
        type: "activity",
        description: "Brincadeiras dirigidas e exploração do espaço externo.",
        classId: "jardim-i",
        date: null,
        projectId: null,
        routineId: null
    },
    {
        id: "5",
        time: "11:30",
        endTime: "13:00",
        title: "Almoço",
        type: "meal",
        description: "Arroz, feijão, legumes e proteína.",
        classId: "jardim-i",
        date: null,
        projectId: null,
        routineId: null
    },
    {
        id: "6",
        time: "13:00",
        endTime: "15:00",
        title: "Descanso / Sono",
        type: "care",
        description: "Momento de repouso.",
        classId: "jardim-i",
        date: null,
        projectId: null,
        routineId: null
    },
    {
        id: "7",
        time: "10:00",
        endTime: "11:30",
        title: "Exploração da Horta",
        type: "project",
        description: "Observação e cuidado com as hortaliças.",
        classId: "jardim-i",
        projectId: "p1",
        date: "2024-02-15",
        routineId: null
    },
    {
        id: "8",
        time: "10:00",
        endTime: "11:30",
        title: "Brincadeiras Matriz Indígena",
        type: "project",
        description: "Vivência de jogos tradicionais brasileiros.",
        classId: "jardim-i",
        projectId: "p3",
        date: "2024-02-18",
        routineId: null
    },
    {
        id: "9",
        time: "10:00",
        endTime: "11:30",
        title: "Oficina de Medidas",
        type: "project",
        description: "Prática de medição com instrumentos diversos.",
        classId: "jardim-i",
        projectId: "p3",
        date: "2024-02-20",
        routineId: null
    }
];
